---
title: "learnr Tutorials"
output: html_notebook
---

This is my work on the learnr tutorials that I found in RStudio. 

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(nycflights13)
library(tidyverse)
```

### Data basics & Filter observations

\ 

#### Datasets (mpg, cars, and flights)

```{r}
mpg
```
\ 

```{r}
as_tibble(cars) # cars did not start out as a tibble, but the others did
```
\ 

```{r}
flights
```

\ 

#### Exercises

I started playing with tidyverse pipes before the later tutorials on them because they're so neat!

**Find all flights that...**

```{r}
# Had an arrival delay of two or more hours
flights %>% 
  mutate(arr_delay_hrs = arr_delay/60) %>% 
  select(arr_delay_hrs, arr_delay, everything()) %>% 
  filter(arr_delay_hrs >= 2) %>% 
  arrange(desc(arr_delay_hrs))

```
\ 

```{r}
# Arrived more than two hours late, but didn’t leave late
flights %>%
  mutate(dep_delay_hrs = dep_delay/60, arr_delay_hrs = arr_delay/60) %>%
  select(dep_delay_hrs, dep_delay, arr_delay_hrs, arr_delay, everything()) %>%
  filter(dep_delay_hrs <= 0, arr_delay_hrs >= 2)

```
\ 

```{r}
# Departed in summer (July, August, and September)
flights %>% filter(between(month, 7, 9)) %>% count(month)

```
\ 

```{r}
# Were delayed by at least an hour, but made up over 30 minutes in flight
flights %>%
  mutate(dep_delay_hrs = dep_delay/60, arr_delay_hrs = arr_delay/60, made_up_mins = dep_delay-arr_delay) %>%
  select(made_up_mins, dep_delay_hrs, dep_delay, arr_delay_hrs, arr_delay, everything()) %>%
  filter(dep_delay_hrs >= 1, made_up_mins >= 30) %>%
  arrange(desc(made_up_mins))

```
\ 

```{r}
# Departed between midnight and 6am (inclusive)
flights %>% 
  filter(dep_time <= 600 | dep_time == 2400) %>% 
  group_by(dep_hour = floor(dep_time/100)) %>%
  count()

```
\ 

```{r}
# my own thing... looking at departure delays by month
flights %>% 
  filter(!is.na(dep_delay)) %>% 
  group_by(month) %>% 
  summarize(mean_dep_delay = mean(dep_delay), min_dep_delay = min(dep_delay), max_dep_delay = max(dep_delay), n())

```

\

```{r}
# Exercise: which carrier has the worst delays?
flights %>% 
  group_by(carrier) %>% 
  summarise(mean_delay = mean(dep_delay, na.rm = TRUE), n()) %>%
  arrange(desc(mean_delay))

```

```{r}
# example of prepping data with pipes then plotting; interesting trend that delays decrease with flight distance
arr_delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    mean_arr_delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
  filter(count > 20, dest != "HNL")


ggplot(data = arr_delays, mapping = aes(x = dist, y = mean_arr_delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)

```
#### example of dynamic graph generation with dygraph

```{r}
library(dygraphs)
lungDeaths <- cbind(mdeaths, fdeaths)

dygraph(lungDeaths) %>% 
  dySeries("mdeaths", label = "Male") %>%
  dySeries("fdeaths", label = "Female") %>%
  dyOptions(stackedGraph = TRUE) %>%
  dyRangeSelector(height = 25)
```

